apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin-service
  template:
    metadata:
      labels:
        app: zipkin-service
    spec:
      containers:
        - name: zipkin-service
          image: zipkin-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9411
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
spec:
  selector:
    app: zipkin-service
  ports:
    - protocol: TCP
      port: 9411
      targetPort: 9411
      nodePort: 30005
  type: NodePort
